// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChy_KsBXmKZuSh3qy6gKN1vVH2n3sLhHw',
    appId: '1:263610461324:android:7deaaa885c7f479dc61fa9',
    messagingSenderId: '263610461324',
    projectId: 'pinterestapp-1cce0',
    databaseURL: 'https://pinterestapp-1cce0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pinterestapp-1cce0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNJmTbh0QZiNCVFWnqajbgL86pkir6BgE',
    appId: '1:263610461324:ios:3ad71b02664b0200c61fa9',
    messagingSenderId: '263610461324',
    projectId: 'pinterestapp-1cce0',
    databaseURL: 'https://pinterestapp-1cce0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pinterestapp-1cce0.appspot.com',
    iosBundleId: 'nematov.dev.painteresClone',
  );
}
